### ISSUE TITLE
🐛 Bug Report: Can't run pocket-id properly

### ISSUE THREAD

**Issue by masbej** [stonith404/pocket-id#40]
### Reproduction steps

I'm using `docker compose file` like this

```yaml
services:
  pocket-id:
    image: stonith404/pocket-id:v0.8.1
    container_name: pocket
    restart: unless-stopped
    env_file: .env
    # ports:
    #   - 3000:80
    volumes:
      - "./data:/app/backend/data"
    networks:
      - proxy

networks:
  proxy:
    external: true
```

and then  `.env`

```
PUBLIC_APP_URL=https://mydomain.example
TRUST_PROXY=true
```

### Expected behavior

The container should run

### Actual Behavior

```
pocket  | Starting frontend...
pocket  | Starting backend...
pocket  | Starting Caddy...
pocket  | {"level":"info","ts":1728733042.0330827,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile.trust-proxy","config_adapter":""}
pocket  | {"level":"info","ts":1728733042.1262019,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//127.0.0.1:2019","//localhost:2019","//[::1]:2019"]}
pocket  | {"level":"warn","ts":1728733042.1297972,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
pocket  | {"level":"info","ts":1728733042.1453056,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000414780"}pocket  | {"level":"info","ts":1728733042.1468096,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
pocket  | {"level":"info","ts":1728733042.1479144,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
pocket  | {"level":"info","ts":1728733042.1534324,"msg":"serving initial configuration"}
pocket  | {"level":"warn","ts":1728733042.1558542,"logger":"tls","msg":"unable to get instance ID; storage clean stamps will be incomplete","error":"open /root/.local/share/caddy/instance.uuid: no such file or directory"}
pocket  | {"level":"info","ts":1728733042.1702383,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/root/.local/share/caddy"}
pocket  | {"level":"info","ts":1728733042.171454,"logger":"tls","msg":"finished cleaning storage units"}
pocket  | Successfully started Caddy (pid=24) - Caddy is running in the background
pocket  | Listening on 0.0.0.0:3000
pocket  | [GIN] 2024/10/12 - 11:37:36 | 401 |      84.558µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:36 | 401 |    1.014974ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:36 | 200 |     524.892µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:36 | 200 |    1.409549ms |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:36 | 401 |      60.229µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:36 | 401 |    1.111748ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:36 | 200 |     888.852µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:36 | 200 |    1.682771ms |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 401 |      45.283µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 401 |    1.352063ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 200 |     352.646µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 200 |    1.006814ms |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 401 |      55.318µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 401 |     697.138µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 200 |     284.761µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 200 |      679.77µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | SvelteKitError: Not found: /api/application-configuration/logo
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
pocket  | }
pocket  | SvelteKitError: Not found: /api/application-configuration/background-image
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
pocket  | }
pocket  | [GIN] 2024/10/12 - 11:37:37 | 401 |      37.769µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 401 |    1.239355ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 200 |     379.124µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:37 | 200 |     951.063µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | SvelteKitError: Not found: /api/application-configuration/favicon
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
pocket  | }
pocket  | [GIN] 2024/10/12 - 11:37:44 | 401 |     128.146µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 401 |    1.220141ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 200 |     314.073µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 200 |     948.323µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 401 |      37.924µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 401 |     949.812µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 200 |     346.672µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 200 |      932.65µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | SvelteKitError: Not found: /api/application-configuration/background-image
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
pocket  | }
pocket  | [GIN] 2024/10/12 - 11:37:44 | 401 |      87.956µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 401 |     972.589µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 200 |      501.85µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:44 | 200 |    1.711877ms |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | SvelteKitError: Not found: /api/application-configuration/logo
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
pocket  | }
pocket  | [GIN] 2024/10/12 - 11:37:46 | 401 |      49.598µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:46 | 401 |    1.191846ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:37:46 | 200 |     362.966µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:37:46 | 200 |      855.79µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | SvelteKitError: Not found: /api/one-time-access-token/setup
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
pocket  | }
^Ccanceled
urra@urra:~/docker/pocket-id$ dcd
[+] Running 1/1
 ✔ Container pocket  Removed                                                                                                                           10.4s 
urra@urra:~/docker/pocket-id$ dcu && dcl
[+] Running 2/2
 ✔ Volume "pocket-id_data"  Created                                                                                                                     0.0s 
 ✔ Container pocket         Started                                                                                                                     0.7s 
pocket  | Starting frontend...
pocket  | Starting backend...
pocket  | Starting Caddy...
pocket  | {"level":"info","ts":1728733144.0010903,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile.trust-proxy","config_adapter":""}
pocket  | {"level":"info","ts":1728733144.0081658,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//[::1]:2019","//127.0.0.1:2019","//localhost:2019"]}
pocket  | {"level":"warn","ts":1728733144.0215242,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
pocket  | {"level":"info","ts":1728733144.0251305,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
pocket  | {"level":"info","ts":1728733144.0262988,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
pocket  | {"level":"info","ts":1728733144.0289369,"msg":"serving initial configuration"}
pocket  | {"level":"info","ts":1728733144.0310507,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000249300"}pocket  | {"level":"warn","ts":1728733144.0330946,"logger":"tls","msg":"unable to get instance ID; storage clean stamps will be incomplete","error":"open /root/.local/share/caddy/instance.uuid: no such file or directory"}
pocket  | {"level":"info","ts":1728733144.0456312,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/root/.local/share/caddy"}
pocket  | {"level":"info","ts":1728733144.046941,"logger":"tls","msg":"finished cleaning storage units"}
pocket  | Successfully started Caddy (pid=25) - Caddy is running in the background
pocket  | Listening on 0.0.0.0:3000
pocket  | [GIN] 2024/10/12 - 11:39:44 | 401 |     138.961µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:44 | 401 |    1.195153ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:44 | 200 |     722.948µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:39:44 | 200 |    1.968506ms |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:39:44 | 401 |      53.665µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:44 | 401 |    1.039612ms |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:44 | 200 |     360.697µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:39:44 | 200 |      978.06µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 401 |      59.843µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 401 |      987.19µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 200 |     384.252µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 200 |    1.053435ms |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 401 |      28.878µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 401 |     855.931µs |       127.0.0.1 | GET      "/api/users/me"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 200 |     323.993µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | [GIN] 2024/10/12 - 11:39:45 | 200 |     887.974µs |       127.0.0.1 | GET      "/api/application-configuration"
pocket  | SvelteKitError: Not found: /api/application-configuration/background-image
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
pocket  | }
pocket  | SvelteKitError: Not found: /api/application-configuration/logo
pocket  |     at resolve2 (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5280:18)
pocket  |     at resolve (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5113:34)
pocket  |     at Object.handle (file:///app/frontend/build/server/chunks/hooks.server-DoTFqLGe.js:41:26)
pocket  |     at respond (file:///app/frontend/build/server/chunks/index-D3dgayUa.js:5111:43) {
pocket  |   status: 404,
pocket  |   text: 'Not Found'
```

When I access the setup url the log show these error messages

**Comment by stonith404** [comment]
On which port does the reverse proxy access Pocket ID?

**Comment by 2TAP2B** [comment]
Im running pocket-id with caddy with no issues

compose.yml
```yaml
services:
  pocket-id:
    image: stonith404/pocket-id:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 3005:80
    volumes:
      - "./data:/app/backend/data"
```

.env
```env
PUBLIC_APP_URL=https://pocket.id
```

Caddyfile
```yaml
# pocket-id
https://pocket.id {

    reverse_proxy http://100.64.0.2:3005
        # Enable HSTS to enforce HTTPS with a max-age of 1 year and include subdomains
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    }

    # Restrict to modern and secure TLS versions only (TLS 1.2 and 1.3)
    tls {
        protocols tls1.2 tls1.3
        ciphers TLS_AES_128_GCM_SHA256 TLS_CHACHA20_POLY1305_SHA256
    }
}
```
maybe this helps

**Comment by masbej** [comment]
> On which port does the reverse proxy access Pocket ID?
I've checked `docker compose ps` the port that open is 3000. But when I changed to 80, it finally run.

**Comment by masbej** [comment]
> Im running pocket-id with caddy with no issues
> 
> compose.yml
> 
> ```yaml
> services:
>   pocket-id:
>     image: stonith404/pocket-id:latest
>     restart: unless-stopped
>     env_file: .env
>     ports:
>       - 3005:80
>     volumes:
>       - "./data:/app/backend/data"
> ```
> 
> .env
> 
> ```dotenv
> PUBLIC_APP_URL=https://pocket.id
> ```
> 
> Caddyfile
> 
> ```yaml
> # pocket-id
> https://pocket.id {
> 
>     reverse_proxy http://100.64.0.2:3005
>         # Enable HSTS to enforce HTTPS with a max-age of 1 year and include subdomains
>     header {
>         Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
>     }
> 
>     # Restrict to modern and secure TLS versions only (TLS 1.2 and 1.3)
>     tls {
>         protocols tls1.2 tls1.3
>         ciphers TLS_AES_128_GCM_SHA256 TLS_CHACHA20_POLY1305_SHA256
>     }
> }
> ```
> 
> maybe this helps

Thank you for your help

**Comment by tajkirkpatrick** [comment]
@masbej do you happen to have any examples of the oath2-proxy container working properly behind Caddy?

I am attempting to follow the guide here within the GitHub but am encountering a callback url error
